name: CI

on: 
  push:
  pull_request_target:
    types: [labeled]

jobs:
  test:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'run tests') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: poetry run pytest -n auto --cov=tested --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./result/coverage.xml
  lint:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'run tests') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop .#format -c poetry run isort --check-only --diff ./tested ./tests
      - run: nix develop .#format -c poetry run black --check ./tested ./tests
  types:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'run tests') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
      - run: nix develop .#types -c pyright ./tested ./tests
