name: CI

on: 
  push:
  pull_request_target:
    types: [labeled]

jobs:
  build_devcontainer:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'run tests') }}
    uses: ./.github/workflows/build_devcontainer.yml
    secrets: inherit
  test:
    needs: [build_devcontainer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Run tests in container
        uses: devcontainers/ci@v0.3
        with:
          imageName: dodona/dodona-tested
          imageTag: dev
          push: never
          runCmd: poetry run pytest -n auto --cov=tested --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./result/coverage.xml
  lint:
    needs: [build_devcontainer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Run isort
        uses: devcontainers/ci@v0.3
        with:
          imageName: dodona/dodona-tested
          imageTag: dev
          push: never
          runCmd: poetry run isort --check-only --diff ./tested ./tests
      - name: Run black
        uses: devcontainers/ci@v0.3
        with:
          imageName: dodona/dodona-tested
          imageTag: dev
          push: never
          runCmd: poetry run black --check ./tested ./tests
  types:
    needs: [build_devcontainer]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Run pyright
        uses: devcontainers/ci@v0.3
        with:
          imageName: dodona/dodona-tested
          imageTag: dev
          push: never
          runCmd: poetry run pyright ./tested ./tests
